#!/usr/bin/env python3
"""Freeze the complete exact-AVX2 top-FF1 backward replay."""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

from enwiki9_python_source_closure import local_source_closure
import nncp_open_profile_top_ff1_bias_gradient_64_q0_v1_materializer as base
import research_contracts


ROOT = Path(__file__).resolve().parents[1]
CANDIDATE_ID = "nncp_open_profile_top_ff1_bias_gradient_avx2_64_q0_v1"
PARENT_ID = "nncp_open_profile_top_ff1_bias_gradient_64_q0_retry_v2"
OUTPUT = ROOT / "operations/adaptive/experiments" / f"{CANDIDATE_ID}.json"
RUNNER = ROOT / (
    "tools/nncp_open_profile_top_ff1_bias_gradient_avx2_64_q0.py"
)
MATERIALIZER = Path(__file__).resolve()
PROGRAM = ROOT / "programs" / CANDIDATE_ID
PARENT_PROGRAM = ROOT / "programs" / PARENT_ID
PARENT_RESULT = ROOT / "results" / PARENT_ID
PARENT_REFLECTION = ROOT / (
    "operations/adaptive/reflections/20260816T095147Z_8ddedba49c.json"
)
PARENT_REVISION = ROOT / (
    "operations/adaptive/candidate-revisions/"
    f"{PARENT_ID}/20260816T095132877494Z_926794f9e1d3.json"
)
BLOCK_RESULT = ROOT / "results/nncp_libnc_ff2_transpose_block128_64_q0_v1"
BLOCK_REFLECTION = ROOT / (
    "operations/adaptive/reflections/20260816T093907Z_7f51e2d346.json"
)
SOURCE_FF2_RESULT = ROOT / "results/nncp_libnc_top_ff2_input_adjoint_64_q0_v1"
AVX2_RESULT = ROOT / "results/nncp_libnc_geglu_gate_avx2_64_q0_v1"
AVX2_REFLECTION = ROOT / (
    "operations/adaptive/reflections/20260816T104055Z_2c469fd001.json"
)
SOURCE_BRANCH_RESULT = ROOT / (
    "results/nncp_libnc_top_geglu_branch_adjoints_64_q0_retry_v2"
)
TAIL_RESULT = ROOT / (
    "results/nncp_open_profile_top_ff2_gradient_stream_dot_64_q0_retry_v2"
)
TAIL_REFLECTION = ROOT / (
    "operations/adaptive/reflections/20260816T082228Z_f0bff9b6df.json"
)
SOURCE_CEILING = 2_000_000


contracts = base.base


def add_measurement(
    measurements: list[dict[str, str]],
    identifier: str,
    unit: str,
    definition: str,
) -> None:
    measurements.append(
        {"id": identifier, "unit": unit, "definition": definition}
    )


def predicate(
    identifier: str, measurement: str, operator: str, threshold: object
) -> dict[str, object]:
    return {
        "id": identifier,
        "measurement": measurement,
        "operator": operator,
        "threshold": threshold,
    }


def main() -> int:
    if OUTPUT.exists():
        raise ValueError(f"experiment already exists: {OUTPUT}")
    experiment = json.loads(
        (ROOT / f"operations/adaptive/experiments/{PARENT_ID}.json").read_text()
    )
    experiment["experimentId"] = CANDIDATE_ID
    experiment["proposalId"] = CANDIDATE_ID
    experiment["parent"] = {
        "candidateId": PARENT_ID,
        "revision": {
            "path": PARENT_REVISION.relative_to(ROOT).as_posix(),
            "sha256": f"sha256:{contracts.sha256(PARENT_REVISION)}",
        },
    }
    experiment["hypothesis"] = {
        "claim": "Installing only the source-exact AVX2 GEGLU gate-backward contract into the exact-FF2 open replay reproduces both complete source branch adjoints and the retained ff_bias1_19 gradient exactly.",
        "falsification": "Any antecedent, forward checkpoint, FF2 residual, gate adjoint, value adjoint, retained bias, replay, control, dependency, source, strict-output, memory, disk, or cleanup failure prevents promotion.",
    }
    experiment["changedMechanism"] = (
        "Replace only scalar libm-tanh GELU backward with the digest-attributed "
        "eight-lane bounded-exp polynomial and FMA order proven exact by the "
        "complete branch-adjoint oracle. Preserve the exact FF2 transpose, "
        "branch multiplication, BF16 boundaries, and bias reduction."
    )
    experiment["invariants"] = [
        "The exact 128-feature FF2 transpose, incoming residual, forward fixtures, sample order, branch multiplication, BF16 boundaries, bias reduction, and sign control remain unchanged.",
        "Only the uniform GEGLU gate derivative arithmetic changes; the value branch remains an exact independent alignment control.",
        "The derived reducer is generated by two unique source replacements before configure and its parent and derived digests are recorded in the build receipt.",
        "Source branch adjoints and the retained ff_bias1_19 comparator are consulted only after complete outputs exist; tolerance and coordinate repair are forbidden.",
        "All teacher artifacts and captured adjoints remain zero-credit and cannot ship in the submitted codec.",
    ]
    experiment["controls"] = [
        {
            "id": "exact-ff2-residual",
            "role": "comparator",
            "definition": "The complete FF2 input residual must remain byte-identical to the independent source capture.",
        },
        {
            "id": "source-gate-adjoint",
            "role": "comparator",
            "definition": "The complete gate branch must match its deterministic source capture exactly.",
        },
        {
            "id": "source-value-adjoint",
            "role": "comparator",
            "definition": "The unchanged value branch must remain exact over the complete population.",
        },
        {
            "id": "exact-avx2-gate",
            "role": "treatment",
            "definition": "Only the GEGLU gate derivative uses the digest-attributed bounded-exp AVX2 instruction contract.",
        },
        {
            "id": "sign-negated-control",
            "role": "negative",
            "definition": "Negating the incoming residual must change the final ff_bias1_19 projection through the same arithmetic.",
        },
        {
            "id": "independent-replay",
            "role": "replay",
            "definition": "Two complete forward/backward populations must be byte-identical before classification.",
        },
    ]
    inputs = [
        contracts.reference(TAIL_RESULT / "decision.json", "tail-decision"),
        contracts.reference(TAIL_RESULT / "execution.json", "tail-execution"),
        contracts.reference(TAIL_RESULT / "guard.json", "tail-guard"),
        contracts.reference(TAIL_REFLECTION, "tail-reflection"),
        contracts.reference(
            TAIL_RESULT / "open-final-norm-input-residual.bf16",
            "promoted-final-rms-input-residual",
        ),
        contracts.reference(PARENT_RESULT / "decision.json", "parent-decision"),
        contracts.reference(PARENT_RESULT / "execution.json", "parent-execution"),
        contracts.reference(PARENT_RESULT / "guard.json", "parent-guard"),
        contracts.reference(PARENT_REFLECTION, "parent-reflection"),
        contracts.reference(
            PARENT_PROGRAM / "top_ff1_bias_gradient.cpp",
            "parent-reducer-source",
        ),
        contracts.reference(BLOCK_RESULT / "decision.json", "block128-decision"),
        contracts.reference(BLOCK_RESULT / "execution.json", "block128-execution"),
        contracts.reference(BLOCK_RESULT / "guard.json", "block128-guard"),
        contracts.reference(BLOCK_REFLECTION, "block128-reflection"),
        contracts.reference(
            BLOCK_RESULT / "block128-ff2-input-adjoint.bf16",
            "block128-ff2-input-adjoint",
        ),
        contracts.reference(
            SOURCE_FF2_RESULT / "decision.json",
            "source-ff2-input-adjoint-decision",
        ),
        contracts.reference(
            SOURCE_FF2_RESULT / "source-ff2-input-adjoint.bf16",
            "source-ff2-input-adjoint",
        ),
        contracts.reference(AVX2_RESULT / "decision.json", "avx2-decision"),
        contracts.reference(AVX2_RESULT / "execution.json", "avx2-execution"),
        contracts.reference(AVX2_RESULT / "guard.json", "avx2-guard"),
        contracts.reference(AVX2_REFLECTION, "avx2-reflection"),
        contracts.reference(
            AVX2_RESULT / "avx2-geglu-gate-adjoint.bf16",
            "avx2-gate-adjoint",
        ),
        contracts.reference(
            AVX2_RESULT / "value-branch-control.bf16", "avx2-value-control"
        ),
        contracts.reference(
            SOURCE_BRANCH_RESULT / "source-geglu-gate-adjoint.bf16",
            "source-geglu-gate-adjoint",
        ),
        contracts.reference(
            SOURCE_BRANCH_RESULT / "source-geglu-value-adjoint.bf16",
            "source-geglu-value-adjoint",
        ),
        contracts.reference(RUNNER, "runner"),
        contracts.reference(MATERIALIZER, "materializer"),
        contracts.reference(
            PARENT_PROGRAM / "materialize_forward.py", "forward-materializer"
        ),
        contracts.reference(PARENT_PROGRAM / "CMakeLists.txt", "cmake-contract"),
        contracts.reference(PROGRAM / "program.py", "program-descriptor"),
    ]
    present = {item["path"] for item in inputs}
    for path in local_source_closure((RUNNER, MATERIALIZER)):
        relative = path.relative_to(ROOT).as_posix()
        if relative not in present:
            inputs.append(
                contracts.reference(path, contracts.source_identifier(path))
            )
            present.add(relative)
    experiment["inputs"] = inputs
    add_measurement(
        experiment["measurements"],
        "sourceGateAdjointMismatchCount",
        "BF16 elements",
        "Complete open gate-branch words differing from source.",
    )
    add_measurement(
        experiment["measurements"],
        "maximumSourceGateAdjointAbsoluteError",
        "float32 value",
        "Maximum absolute open/source gate-branch difference.",
    )
    add_measurement(
        experiment["measurements"],
        "sourceValueAdjointMismatchCount",
        "BF16 elements",
        "Complete unchanged value-branch words differing from source.",
    )
    add_measurement(
        experiment["measurements"],
        "maximumSourceValueAdjointAbsoluteError",
        "float32 value",
        "Maximum absolute open/source value-branch difference.",
    )
    experiment["promotionPredicates"].extend(
        [
            predicate(
                "p-source-gate", "sourceGateAdjointMismatchCount", "eq", 0
            ),
            predicate(
                "p-source-gate-maximum",
                "maximumSourceGateAdjointAbsoluteError",
                "eq",
                0,
            ),
            predicate(
                "p-source-value", "sourceValueAdjointMismatchCount", "eq", 0
            ),
            predicate(
                "p-source-value-maximum",
                "maximumSourceValueAdjointAbsoluteError",
                "eq",
                0,
            ),
        ]
    )
    experiment["killPredicates"].extend(
        [
            predicate(
                "k-source-gate", "sourceGateAdjointMismatchCount", "gt", 0
            ),
            predicate(
                "k-source-value", "sourceValueAdjointMismatchCount", "gt", 0
            ),
        ]
    )
    experiment["outputs"] = [
        f"results/{CANDIDATE_ID}/decision.json",
        f"results/{CANDIDATE_ID}/execution.json",
        f"results/{CANDIDATE_ID}/open-ff2-input-residual.bf16",
        f"results/{CANDIDATE_ID}/open-ff1-output-residual.bf16",
        f"results/{CANDIDATE_ID}/open-ff-bias1-19-gradient.bf16",
        f"results/{CANDIDATE_ID}/incremental_source.tar.xz",
    ]
    experiment["generatedUtc"] = (
        dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    )
    OUTPUT.write_text(json.dumps(experiment, indent=2, sort_keys=True) + "\n")
    try:
        research_contracts.validate_artifact(OUTPUT)
    except Exception:
        OUTPUT.unlink(missing_ok=True)
        raise
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
