"""numeric_v1 — semantic compression of ISO dates (YYYY-MM-DD), then lzma -9e.

Conservative implementation: only ISO 8601 dates between 1500-01-01 and
2199-12-31. Encodes each as a 3-byte days-since-1500-01-01 integer wrapped
in a 2-byte marker `0x11 0xff`.

Frame format inside the substitution stream (before lzma):
    raw bytes... 0x11 0xff [3-byte BE days] raw bytes...
    0x11 in the input becomes 0x11 0x00 (escape doubling)

So 0x11 in encoded stream is always a marker:
    0x11 0x00 → literal 0x11 byte
    0x11 0xff → date marker; next 3 bytes are days-since-1500
    other      → undefined (input was not generated by this encoder)

Reversibility: decode walks the stream, sees each 0x11, branches on the
following byte.
"""

from __future__ import annotations

import datetime as _dt
import lzma
import re

PRESET = 9 | lzma.PRESET_EXTREME

ISO_DATE_RE = re.compile(
    rb"(?<![0-9])((?:1[5-9]|20|21)[0-9]{2})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])(?![0-9])"
)

ESC = 0x11
DATE_TAG = 0xFF
EPOCH = _dt.date(1500, 1, 1)


def _encode_date(y: int, m: int, d: int) -> bytes | None:
    try:
        delta = (_dt.date(y, m, d) - EPOCH).days
    except ValueError:
        return None
    if delta < 0 or delta >= (1 << 24):
        return None
    return delta.to_bytes(3, "big")


def _double_esc(chunk: bytes) -> bytes:
    return chunk.replace(bytes([ESC]), bytes([ESC, 0x00]))


def _encode(data: bytes) -> bytes:
    parts: list[bytes] = []
    pos = 0
    for m in ISO_DATE_RE.finditer(data):
        parts.append(_double_esc(data[pos : m.start()]))
        y = int(m.group(1))
        mo = int(m.group(2))
        d = int(m.group(3))
        encoded = _encode_date(y, mo, d)
        if encoded is None:
            parts.append(_double_esc(m.group(0)))
        else:
            parts.append(bytes([ESC, DATE_TAG]) + encoded)
        pos = m.end()
    parts.append(_double_esc(data[pos:]))
    return b"".join(parts)


def _decode(stream: bytes) -> bytes:
    out: list[bytes] = []
    pos = 0
    n = len(stream)
    while pos < n:
        i = stream.find(bytes([ESC]), pos)
        if i < 0:
            out.append(stream[pos:])
            break
        out.append(stream[pos:i])
        pos = i + 1
        if pos >= n:
            raise ValueError("trailing ESC with no marker")
        tag = stream[pos]
        pos += 1
        if tag == 0x00:
            out.append(bytes([ESC]))
        elif tag == DATE_TAG:
            days = int.from_bytes(stream[pos : pos + 3], "big")
            pos += 3
            date = EPOCH + _dt.timedelta(days=days)
            out.append(
                f"{date.year:04d}-{date.month:02d}-{date.day:02d}".encode("ascii")
            )
        else:
            raise ValueError(f"bad marker {tag:#x} at offset {pos - 1}")
    return b"".join(out)


def compress(data: bytes) -> bytes:
    return lzma.compress(_encode(data), preset=PRESET)


def decompress(data: bytes) -> bytes:
    return _decode(lzma.decompress(data))
