"""Bounded byte equivalence and separately delivered codec; no corpus access."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

import pytest

from gamma_enwiki9.adapters.raw_reverse_comparison import run
from gamma_enwiki9.evidence.artifacts import fingerprint
from gamma_enwiki9.evidence.resolver import ArtifactResolver
from gamma_enwiki9.execution.commands import CommandExecutor, PhaseLimits
from gamma_enwiki9.execution.native import NativeGate
from gamma_enwiki9.execution.sandbox import python_command
from gamma_enwiki9.packaging.raw_reverse import build
from gamma_enwiki9.types import BuildProfile, ExecutionContext, ResourceBudget

PROJECT = Path(__file__).resolve().parents[2]


def context(path):
    return ExecutionContext("migration-fixture", PROJECT, path,
        ResourceBudget((min(os.sched_getaffinity(0)),), 1024**3, 32*1024**2, 60),
        BuildProfile((), ()), (("PATH", "/usr/bin:/bin"), ("LC_ALL", "C"), ("PYTHONDONTWRITEBYTECODE", "1")))


def package(path):
    return build(PROJECT / "lib/coders/raw_reverse_bz2.py", PROJECT.parents[1] / "LICENSE", path)


def load_original():
    spec = importlib.util.spec_from_file_location("original_raw_reverse", PROJECT / "tools/raw_reverse_bz2_v1.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_known_recipe_preserves_archives_witnesses_and_command_geometry(tmp_path, monkeypatch):
    package(tmp_path / "package")
    work = tmp_path / "work"
    work.mkdir()
    population = tmp_path / "population"
    raw = b"The fixed synthetic comparison.\n" * 41 + bytes(range(256))
    population.write_bytes(raw)
    result = run(CommandExecutor(context(work)), codec=tmp_path / "package/codec.py",
        population=population, population_sha256=hashlib.sha256(raw).hexdigest(),
        limits=PhaseLimits(10, 10, 1024**3, 8*1024**2))
    original = load_original()
    # Execute the frozen runner independently, then compare its actual command
    # records. No expected commands are generated by the migrated recipe itself.
    spec = importlib.util.spec_from_file_location("migration_original_gate", PROJECT / "tools/raw_reverse_bz2_gate_v1.py")
    gate = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gate)
    old_output = tmp_path / "results/original"
    old_output.mkdir(parents=True)
    (tmp_path / "tools").mkdir()
    shutil.copyfile(PROJECT / gate.CODEC, tmp_path / gate.CODEC)
    plan = {"stage": "development", "population": {"path": "population", "bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()},
        "block_size": 250000, "phase_cpu_seconds": 10, "phase_wall_seconds": 10,
        "phase_address_bytes": 1024**3}
    monkeypatch.setattr(gate, "ROOT", tmp_path)
    monkeypatch.setattr(gate.driver, "ROOT", tmp_path)
    monkeypatch.setattr(gate, "authenticate", lambda *args: ({}, {}, plan))
    monkeypatch.setenv("GAMMA_RESOURCE_PHASE_MARKERS", str(tmp_path / "original-phases.jsonl"))
    assert gate.main(["--candidate", "original"]) == 0
    historical = json.loads((old_output / "stage-decision.json").read_bytes())
    def geometry(argv, codec, output):
        return [arg.replace(str(codec), "<codec>").replace(str(output), "<output>") for arg in argv]
    assert result["evidence"]["verified"]
    assert result["execution"]["classification"] == "completed"
    assert len(result["commands"]) == 9
    for arm in ("P", "K", "D"):
        archive, report = original.encode(raw, arm)
        assert (work / (arm + ".rbz")).read_bytes() == archive
        assert json.loads((work / (arm + "-encode.stdout")).read_bytes()) == report
        assert (old_output / (arm + ".rbz")).read_bytes() == (work / (arm + ".rbz")).read_bytes()
    assert [geometry(r["argv"], tmp_path / "package/codec.py", work) for r in result["commands"]] == [
        geometry(r["argv"], tmp_path / gate.CODEC, old_output) for r in historical["commands"]]
    assert result["decision"]["outcome"] in ("supported", "rejected")
    assert result["objective_credit_bytes"] == 0


@pytest.mark.skipif(shutil.which("bwrap") is None, reason="restricted Linux release lane requires bubblewrap")
def test_package_decodes_without_checkout_or_observer_imports(tmp_path):
    manifest = package(tmp_path / "package")
    source = tmp_path / "input"
    source.mkdir()
    raw = b"independent package fixture" * 11
    archive = load_original().encode(raw)[0]
    (source / "archive").write_bytes(archive)
    output = tmp_path / "output"
    output.mkdir()
    argv = python_command(readonly={tmp_path / "package": "/package", source: "/input"},
        writable={output: "/output"}, argv=["/package/codec.py", "decode", "/input/archive", "/output/restored"], cwd="/package")
    result = subprocess.run(argv, capture_output=True, timeout=15)
    assert result.returncode == 0, result.stderr
    assert (output / "restored").read_bytes() == raw
    assert manifest["observer_dependencies"] == manifest["experiment_dependencies"] == []
    assert manifest["counted_source_bytes"] == sum((tmp_path / "package" / r["path"]).stat().st_size for r in manifest["files"])


def test_streaming_resolver_refuses_unbounded_buffer(tmp_path):
    source = tmp_path / "large"
    source.write_bytes(b"a" * 4096)
    resolver = ArtifactResolver(tmp_path, (fingerprint(source, tmp_path),), buffer_limit=16)
    with pytest.raises(ValueError, match="buffer limit"):
        resolver.read_source("large")
    resolver.copy("large", tmp_path / "copy")
    assert (tmp_path / "copy").read_bytes() == source.read_bytes()


@pytest.mark.native
@pytest.mark.skipif(shutil.which("gcc") is None, reason="native fixture lane requires gcc")
def test_native_synthetic_roundtrip_under_undefined_behavior_sanitizer(tmp_path):
    source = PROJECT / "tests/fixtures/enwiki9_release_canary/package/codec.c"
    compiler = Path(shutil.which("gcc")).resolve()
    ctx = context(tmp_path)
    ctx = ExecutionContext(ctx.job_id, ctx.snapshot_root, ctx.workspace, ctx.budget,
        BuildProfile((str(compiler), "-fsanitize=undefined,bounds"),
            ((str(compiler), fingerprint(compiler, compiler.parent)["sha256"]),)), ctx.environment)
    gate = NativeGate(ctx, resolver=ArtifactResolver(PROJECT, (fingerprint(source, PROJECT),)), executor=CommandExecutor(ctx))
    gate.copy(source.relative_to(PROJECT).as_posix(), tmp_path / "codec.c")
    limits = PhaseLimits(10, 15, 1024**3, 4*1024**2)
    outcome, _ = gate.run("build", [str(compiler), "-std=c99", "-fsanitize=undefined,bounds", "-fno-sanitize-recover=all", "codec.c", "-o", "codec"], limits)
    assert outcome.classification == "completed"
    raw = b"a" * 1024 + bytes(range(256))
    (tmp_path / "input").write_bytes(raw)
    for phase, argv in (("encode", [str(tmp_path / "codec"), "c", "input", "archive"]),
                        ("decode", [str(tmp_path / "codec"), "d", "archive", "restored"])):
        outcome, _ = gate.run(phase, argv, limits)
        assert outcome.classification == "completed"
    assert (tmp_path / "restored").read_bytes() == raw
